### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by Errorkiller** [JZhaoCH/dcgan-tensorflow#1]
hi,
I have read your other projects and are very interested in your matconvnet. Are you interested in converting DCGAN to matconvnet version?

**Comment by jonzhaocn** [comment]
Hi, there are already exists DCGANs in matconvnet version, like [mcnDCGAN](https://github.com/hbilen/mcnDCGAN) and [dcgan-matconvnet](https://github.com/sunghbae/dcgan-matconvnet), hope them could help you.

**Comment by Errorkiller** [comment]
Thanks a lot!

**Comment by Errorkiller** [comment]
I am also learning matconvnet and GAN. I think your work is very good. Can you recommend any better learning resources?

**Comment by jonzhaocn** [comment]
the list of learning resources:
1. [from-GAN-to-WGAN](https://lilianweng.github.io/lil-log/2017/08/20/from-GAN-to-WGAN.html)
2. [令人拍案叫绝的Wasserstein GAN](https://zhuanlan.zhihu.com/p/25071913)
3. [WGAN-tensorflow](https://github.com/Zardinality/WGAN-tensorflow)
4. [unified-gan-tensorflow](https://github.com/lilianweng/unified-gan-tensorflow)
5. [matconvnet](http://www.vlfeat.org/matconvnet/)
